apps/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('addbillingapp/', views.addbillingapp, name='addbillingapp'),
    path('addnonbillingapp/', views.addnonbillingapp, name='addnonbillingapp'),
    path('editapp/<str:aslug>/<int:billing_slug>/', views.editapp, name='editapp'),
    path('all/', views.showapps, name='showapps'),
    path('deleteapp/<aslug>',views.deleteapp,name='deleteapp'),
    path('remove-customer/<str:slug>/<str:userslug>/<int:billing_slug>/',views.remove_user,name='remove-customer'),
    path('<int:billing_slug>/<slug>/', include('dashboard.urls')),
]

billapp_main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('billapp.urls')),
    path('account/', include('accounts.urls')),
    path('<int:billing_slug>/groups/', include('groups.urls')),
    path('<int:billing_slug>/plans/', include('plans.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

groups/urls.py
from django.urls import path, include
from .views import *
from django.contrib.auth import views as a_views

app_name='groups'

urlpatterns = [
    path('panel/<str:slug>', groups_panel, name='groups-panel'),
    path('delete-group/<str:slug>/<str:appslug>', delete_group, name='delete-group'),
    path('group/<str:slug>/<str:groupslug>', show_group, name='group'),
    path('add-member/<str:groupslug>', add_customer_to_group, name='add-member'),
    path('remove-member/<str:groupslug>', remove_customer_from_group, name='remove-member'),
    # path('update-group/<str:slug>/<str:groupslug>', update_user_group, name='update-group'),
    path('plangroup/<str:slug>/<str:plangroupslug>', show_plan_group, name='plangroup'),

]

groups/models.py
from django.db import models
from accounts.models import *
from apps.models import *

# Create your models here.

def generate_code_group():
    length=10
    base = string.ascii_lowercase+string.ascii_uppercase+string.digits
    while True:
        code = ''.join(random.choices(base, k=length))
        if Group.objects.filter(slug=code).count()==0:
            break
    return code

class Group(models.Model):
    slug = models.CharField(max_length=20, default=generate_code_group, editable=False)
    members = models.ManyToManyField(Profile)
    title = models.CharField(max_length=200)
    app = models.ForeignKey(applists, on_delete=models.CASCADE)
    description = models.TextField(max_length=800)
    
    def __str__(self):
        return self.title
    

groups/forms.py
from django import forms
from .models import *
from django.contrib.admin import widgets
from ckeditor.widgets import CKEditorWidget
from accounts.models import *

class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ('title', 'description')
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'ex: Basic, Premium, Standard ...', 'class': 'w3-input w3-border w3-round'}),
            'description': forms.Textarea(attrs={'placeholder': 'overview', 'class': 'w3-input w3-border w3-round'}),
        }


class SubscribeForm(forms.Form):
    username = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={'placeholder': 'username', 'class': 'w3-input w3-border w3-round'})
    )

class UpdateUserGroupForm(forms.Form):
    choice = [
        (1,1)
    ]

    def __init__(self, appslug=None, *args, **kwargs):
        super(UpdateUserGroupForm, self).__init__(*args, **kwargs)
        plans = Group.objects.filter(app__slug=appslug)
        plans_ = []
        for plan in plans:
            plan_ = (plan.id, plan)
            plans_.append(plan_)
        self.fields['update_to'].choices = plans_

    update_to = forms.ChoiceField(
                    choices=choice, 
                    widget=forms.Select(attrs={'placeholder': 'select plan for user ', 'class': 'w3-input w3-border w3-round'}),
                )

groups/views.py
from django.shortcuts import render, redirect
from accounts.models import *
from .models import *
from datetime import date
from django.http import JsonResponse
from .forms import *

# Create your views here.


def groups_panel(request, slug, billing_slug):
    if request.user.is_superuser:
        if request.method == 'GET':
            groups = Group.objects.filter(app__slug=slug)
            plans = Plan.objects.filter(app__slug = slug)
            form = GroupForm()
            payload = {
                'groups': groups,
                'form': form,
                'slug': slug,
                'plans' : plans,
                'billing_slug':billing_slug
            }
            return render(request, 'groups-panel/panel.html',payload)
        
        form = GroupForm(request.POST)
        if form.is_valid():
            group = form.save(commit=False)
            group.app = applists.objects.get(slug=slug)
            group.save()
            return redirect('groups:groups-panel', billing_slug, slug)
        print(form.errors)
        return redirect('groups-panel', billing_slug, slug)
    return redirect('index')

def delete_group(request, slug, appslug, billing_slug):
    group = Group.objects.get(slug__iexact=slug)
    group.delete()
    return redirect('groups:groups-panel', billing_slug, appslug)

def show_group(request, slug, groupslug, billing_slug):
    if request.user.is_superuser:
        if request.method == 'GET':
            group = Group.objects.filter(slug=groupslug).first()
            users = group.members.all()
            form = SubscribeForm()
            existing_users = Profile.objects.filter(apps=group.app).exclude(group=group)
            payload = {
                'group': group,
                'users': users,
                'form': form,
                'update_form': UpdateUserGroupForm(appslug=group.app.slug),
                'slug': slug,
                'existing_users': existing_users,
                'billing_slug' : billing_slug
            }
            return render(request, 'groups-panel/group.html', payload)
        
        # 'POST' method
        form = SubscribeForm(request.POST)
        group = Group.objects.filter(slug=groupslug).first()
        if form.is_valid():
            #if form.cleaned_data.get("username")!='username':
            customer = Profile.objects.filter(user__username=form.cleaned_data.get("username")).filter(apps__in=[group.app])
            if customer.exists():
                customer = customer.first()
                # pre_group = customer.group_set.filter(app__appname=group.app.appname).first()
                # if pre_group:
                #     pre_group.members.remove(customer)
                #create_history(user=customer.user, to_group=group, from_group=customer.group, upgrade=True)
                group.members.add(customer)
            return redirect('groups:group', billing_slug, slug)

            """students = Profile.objects.filter(institute_name=form.cleaned_data.get("institution"), is_student=True)
            for student in students:
                if student.group==group:
                    pass
                create_history(user=student.user, to_group=group, from_group=student.group, upgrade=True)
                student.group = group
                student.save(update_fields=['group'])
            return redirect('group', slug)"""
        print(forms.error)
        return redirect('group', billing_slug, slug)

def add_customer_to_group(request, groupslug, billing_slug):
    username = request.GET.get('username')
    user = Profile.objects.get(user__username=username)

    group = Group.objects.get(slug=groupslug)
    
    # pre_group = user.group_set.filter(app__appname=group.app.appname).first()
    # if pre_group:
    #     pre_group.members.remove(user)

    group.members.add(user)
    return JsonResponse({})

def remove_customer_from_group(request, groupslug, billing_slug):
    username = request.GET.get('username')
    user = Profile.objects.get(user__username=username)

    group = Group.objects.get(slug=groupslug)

    group.members.remove(user)
    return JsonResponse({})



# def update_user_group(request, slug, groupslug):
#     profile = Profile.objects.get(slug__iexact=slug)

#     current_group = Group.objects.get(slug=groupslug)
#     new_group = Group.objects.get(id=request.POST.get('update_to'))

#     current_group.members.remove(profile)
#     new_group.members.add(profile)

#     return redirect('groups:groups-panel', current_group.app.slug)
    """if form.is_valid():
        new_group = group.objects.create(
            title=form.cleaned_data.get("title"),
            price=form.cleaned_data.get("price"),
            description=current_group.description,
            duration=current_group.duration,
            is_dummy=True
        )
        create_history(user=profile.user, to_group=new_group, from_group=current_group, upgrade=True)"""
        

def show_plan_group(request, slug, plangroupslug, billing_slug):
    if request.user.is_superuser:
        if request.method == 'GET':
            plan = Plan.objects.filter(slug=plangroupslug).first()
            users = Profile.objects.filter(plans=plan)
                    
            payload = {
                'plan': plan,
                'users': users,
                'slug' : slug,
                'billing_slug' : billing_slug
            }
            return render(request, 'groups-panel/plangroup.html', payload)

templates/groups-panel/group.html
{% load crispy_forms_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>billsnap</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous" />
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
        integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous">
        </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous">
        </script>
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
        href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200;0,300;0,400;0,500;0,700;0,800;1,200;1,300;1,400;1,500;1,600;1,700&display=swap"
        rel="stylesheet" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'assets/styles.css'%}">
    <link rel="stylesheet" href="{% static 'w3.css' %}" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js" ></script>
</head>
<style>
    .first-sidebar {
			position: fixed;
			top: 76px;
			left: 0;
		}

		.second {
			visibility: hidden;
		}
    /* .row {
        display: flex;
        align-items: center;
        justify-content: center;
        margin-bottom: 20px !important;

    }

    .container {
        max-width: 800px !important;

    }

    .app-form-container {
        max-width: 700px;
    }

    button {
        float: right;
    }

    .grp {
        background-color: white;
        border-radius: 10px;
    }

    .new-group-btn {
        float: right;
        position: relative;
        top: 0;
        right: 0;
    }

    .span {
        background-color: #7b7b7b !important;
        position: relative;
        top: 0;
        right: 0;
        float: right !important;
    }

    .box {
        height: 250px !important;
    }

    b {
        color: #7b7b7b;
    } */
</style>


<body class="w3-padding">

    {% include "dashnav.html" %}

    <div class="main mx-auto">
        <div class="row">


            <!-- sidebar start -->
            {% include "dashsidebar.html" %}

            <!-- sidebar -->
            

                  
       
           

            <!-- main content -->
            <div class="col-md-7  flex-md-fill m-3">
                <div class="col right ps-0 pe-4 me-2" id="">
                    <button class="button button1" data-toggle="modal"
                    data-target="#addcustomer">Add</button>
                    <h2 class="ps-1 pt-3 text-uppercase" id="pspt">{{group}} Customers</h2><br>

                    <!-- table -->
                    <div class="my-3">
                        <table class="table table-bordered" id='table_filter'>
                          <thead>
                            <tr>
                              <th>User Name</th>
                              <th>Full Name</th>
                              <th>Email</th>
                              <th>Status</th>
                            </tr>
                          </thead>
                          <tbody>
                            {% for user in users%}
                            <tr>
                              <td>{{ user.user.username}}</td>
                              <td>{{ user.full_name}}</td>
                              <td>{{ user.contact_email}}</td>
                              <td>{{ user.paid}}</td>
                            </tr>
                            {%endfor%}
                          </tbody>
                        </table>
                      </div>
                    
                    
                </div>
            </div>
        </div>

        <!-- add group model -->
        <div class="modal fade" id="addcustomer" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
            aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-lg" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">Add Customers to {{group.title}}</h5>
                    </div>

                    <div class="modal-body">
                        
                        <div class="table-responsive my-3">
                            <table class="table table-bordered" id='table_filter2'>
                              <thead>
                                <tr>
                                  <th>User Name</th>
                                  <th>Full Name</th>
                                  
                                  
                                  <th>Action</th>
                                </tr>
                              </thead>
                              <tbody>
                                {% for user in existing_users %}
                                <tr>
                                  <td>{{ user.user.username}}</td>
                                  <td>{{ user.full_name}}</td>
                                  <td>
                                    <button class='bs-primary py-2 px-3' onclick="addCustomerApp(this);"
                                    value="{{user.user.username}}" url="{% url 'groups:add-member' billing_slug=billing_slug groupslug=group.slug %}">
                                    Add
                                </button>
                                  </td>
                                </tr>
                                {%endfor%}
                              </tbody>
                            </table>
                          </div>
                        <hr>
                        <!-- <form id="group_form" enctype='multipart/form-data' method='POST'
                            action="{% url 'groups:group' billing_slug=billing_slug slug=slug groupslug=group.slug %}">
                            <h5>Add by Username</h5>
                            {% csrf_token %}
                            {{ form|crispy }}
                            
                                <button type='submit'
                                class='bs-primary py-2 px-3'>Add</button>
                           
                        </form> -->
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="bs-primary bs-secondary px-3 py-2 mx-2"
                            data-dismiss="modal">Close</button>
                    </div>





                </div>
            </div>
        </div>




    </div>

</body>
<script>
    $(document).ready( function () {
    $('#table_filter').DataTable();
} );
</script>
<script>
    $(document).ready( function () {
    $('#table_filter2').DataTable();
} );
</script>
<script>
    function showForm() {
        document.getElementById('group_form').style.display = "block";
        document.getElementById('button').style.display = "none";
    }
    function showUpdateForm() {
        document.getElementById('form').style.display = "block";
    }
    function addCustomerApp(obj) {
        var url = obj.getAttribute('url') + '?username=' + obj.value;
        $.ajax({
            type: 'GET',
            url: url,
            success: function (resp) {
                document.location.reload(true);
            }
        })
    } 
</script>

</html>

templates/groups-panel/panel.html
{% load crispy_forms_tags %}
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>billsnap</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous" />
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
        integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous">
        </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous">
        </script>
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
        href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200;0,300;0,400;0,500;0,700;0,800;1,200;1,300;1,400;1,500;1,600;1,700&display=swap"
        rel="stylesheet" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'assets/styles.css'%}">
</head>
<style>
    /* .row {
        display: flex;
        align-items: center;
        justify-content: center;
        margin-bottom: 20px !important;

    } */

    .container {
        max-width: 800px !important;

    }

    .app-form-container {
        max-width: 700px;
    }

    button {
        float: right;
    }

    .card{
        background-color: #f2f2f2;
        border-radius: 10px;
        margin: 20px;
        width: 300px;
        min-height:230px;
        display:flex;
        flex-direction: column;
        justify-content: space-between;
    }

    .new-group-btn {
        float: right;
        position: relative;
        top: 0;
        right: 0;
    }

    .span {
        background-color: #7b7b7b !important;
        position: absolute;
        top: 10px;
        right: 10px;
        float: right !important;
    }
</style>

<body>
    {% include "dashnav.html" %}

    <div class="main mx-auto">
        <div class="row bulkuploadcontent">

            {% include "dashsidebar.html" %}
            <div class="col-md-7  flex-md-fill m-3 px-3">

                <button class=" button button1" data-toggle="modal" data-target="#addgrp">Add</button>
                <h2 class="ps-1 pt-3 text-uppercase" id="pspt">{{slug}} groups</h2><br>

                <!-- tabs bar -->
                <ul class="nav nav-tabs" id="myTab" role="tablist">
                    <li class="nav-item" role="presentation">
                        <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home"
                            type="button" role="tab" aria-controls="home" aria-selected="true">User Groups</button>
                    </li>
                    {% if is_billing %}
                    <li class="nav-item" role="presentation">
                        <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile"
                            type="button" role="tab" aria-controls="profile" aria-selected="false">Plan Groups</button>
                    </li>
                    {% endif %}

                </ul>
                <div class="tab-content" id="myTabContent">

                    <!-- tab 1 -->
                    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                        <div class="row">
                            {% for group in groups %}
                            
                            <div class="col-xl-3 col-sm-6 mb-5">
                                <div class="card rounded shadow-sm py-4 px-4">
                                    <div class="top">
                                        <h5>{{group.title}}</h5>
                                        <p>{{group.description}}</p>
                                    </div>
                                  <div class="bottom">
                                    <a href="{% url 'groups:group' billing_slug=billing_slug slug=slug groupslug=group.slug %}">
                                        <button class='bs-primary px-3 py-2'>View</button>
                                    </a>
                                    <a href="{% url 'groups:delete-group' billing_slug group.slug slug %}">
                                        <button class='bs-primary bs-secondary px-3 py-2'>Delete</button>
                                    </a> 
                                  </div>
                               
                                </div>
                            </div>
                            
                          
                            {% endfor %}
                        </div>
                        
                    </div>

                    <!-- tab 2 -->
                    <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                        <div class="row">


                            {% for plan in plans %}
                            {% if plan.default_for_customer %}
                            <div class="col-xl-3 col-sm-6 mb-5">
                                <div class="card rounded shadow-sm py-4 px-4">
                                    <div class="top">
                                        <div>
                                            <span class="badge badge-success p-2 mt-2 float-right span">Default</span>
                                        </div>
                                        <h5>{{plan.title}}</h5>
                                        <p>{{plan.description}}</p>
                                    </div>
                                    <div class="bottom">
                                        <a href="{% url 'groups:plangroup' billing_slug slug plan.slug %}">
                                            <button class='bs-primary px-3 py-2'>View</button>
                                        </a>
                                    </div>
                                   
                                </div>
                            </div>
                            
                            {% else %}
                           
                            <div class="col-xl-3 col-sm-6 mb-5">
                                <div class="card rounded shadow-sm py-4 px-4">
                                    <div class="top">
                                        <h5>{{plan.title}}</h5>
                                        <p>{{plan.description}}</p>
                                    </div>
                                   <div class="bottom">
                                    <a href="{% url 'groups:plangroup' slug plan.slug %}">
                                        <button class='bs-primary px-3 py-2'>View</button>
                                    </a>
                                   </div>
                                </div>
                            </div>
                            {% endif %}
                            {% endfor %}
                        </div>
                    </div>

                </div>

            </div>



        </div>
        <!-- add group model -->
        <div class="modal fade" id="addgrp" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
            aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">Create New Group</h5>
                    </div>
                    <form id="group_form" enctype='multipart/form-data' method='POST'
                        action="{% url 'groups:groups-panel' billing_slug slug %}">
                        {% csrf_token %}
                        <div class="modal-body">
                            {{ form|crispy }}



                        </div>
                        <div class="modal-footer">
                            <button type="button" class="bs-primary bs-secondary px-3 py-2 mx-2"
                                data-dismiss="modal">Close</button>
                            <button type="submit" class="bs-primary px-3 py-2">Create</button>
                        </div>


                    </form>


                </div>
            </div>
        </div>
</body>


</html>