accounts/urls.py
from django.urls import path
from accounts import views as acc_views
from django.contrib.auth import views as a_views

app_name='accounts'

urlpatterns = [
    path('register/', acc_views.RegistrationView.as_view(), name='register'),

    path('register/<str:appslug>/<int:billing_slug>/', acc_views.app_registration, name='register-app'),
    
    path('login/', acc_views.LoginView.as_view(), name='login'),
    path('logout/', acc_views.logout, name='logout'),
    path('activate/<uidb64>/<token>', acc_views.VerificationView.as_view(), name='activate'),
    path('reset_password/', acc_views.PasswordResetView.as_view(template_name='password_reset.html'), name='reset-password'),
    path('reset_password_sent/', a_views.PasswordResetDoneView.as_view(template_name='password_reset_sent.html'), name='password-reset-done'),
    path('reset/<uidb64>/<token>/', a_views.PasswordResetConfirmView.as_view(template_name='password_reset_form.html'), name='password-reset-confirm'),
    path('reset_password_complete/', a_views.PasswordResetCompleteView.as_view(template_name='password_reset_done.html'), name='password-reset-complete'),
    path('<str:slug>/edit/<str:userslug>/<int:billing_slug>/', acc_views.update_profile, name='update-profile'),
    path('<str:slug>/<str:userslug>/<int:billing_slug>/', acc_views.ShowProfile.as_view(), name='show-profile'),
    path('<str:slug>/<str:userslug>/<str:planslug>/<int:billing_slug>/', acc_views.update_plan, name='update-plan'),

    path('create-notification/<str:slug>/<int:billing_slug>/', acc_views.create_notification, name='create-notification'),
]

apps/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('addbillingapp/', views.addbillingapp, name='addbillingapp'),
    path('addnonbillingapp/', views.addnonbillingapp, name='addnonbillingapp'),
    path('editapp/<str:aslug>/<int:billing_slug>/', views.editapp, name='editapp'),
    path('all/', views.showapps, name='showapps'),
    path('deleteapp/<aslug>',views.deleteapp,name='deleteapp'),
    path('remove-customer/<str:slug>/<str:userslug>/<int:billing_slug>/',views.remove_user,name='remove-customer'),
    path('<int:billing_slug>/<slug>/', include('dashboard.urls')),
]

billapp_main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('billapp.urls')),
    path('account/', include('accounts.urls')),
    path('<int:billing_slug>/groups/', include('groups.urls')),
    path('<int:billing_slug>/plans/', include('plans.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path, include
from . import views
urlpatterns = [
    path('dashboard/',views.dashboard, name='dashboard'),
    path('estimates/',views.estimate, name='estimates'),
    path('appinfo/',views.appinfo, name='appinfo'),
    path('customerlist/',views.customerlist,name='customerlist'),
    path('addcustomer/', views.addingcustomer, name='addcustomer'),
    path('deletecustomer/<utility_name>',views.deletecust,name='deletecustomer'),
    path('update/<int:id>', views.updaterecord, name='updaterecord'),
    path('bulkupload/', views.bulk_upload, name='bulkupload'),
    path('uploadlist/', views.uploadlis, name='uploadlist'),
    path('add-customer-form/', views.add_customer_form, name='addcustomer'),
    path('add-existing-user/', views.add_existing_user, name='add-existing-user'),
    path('add-customer-app/', views.add_customer_app, name='add-customer-app'),
    path('new-customer/', views.addcustomer, name='new-customer'),
    path('update-profile-plan/<str:slug>', views.update_profile_plan, name='update-profile-plan'),
    path('messaging/', views.messaging, name='messaging'),
    path('notify/<slug:profile_slug>/', views.notification, name='notify'),
    path('pendingapprovals/', views.pendingapproval, name='pending-approvals'),
    path('transactions/',views.transactions, name='transactions'),

]

groups/urls.py
from django.urls import path, include
from .views import *
from django.contrib.auth import views as a_views

app_name='groups'

urlpatterns = [
    path('panel/<str:slug>', groups_panel, name='groups-panel'),
    path('delete-group/<str:slug>/<str:appslug>', delete_group, name='delete-group'),
    path('group/<str:slug>/<str:groupslug>', show_group, name='group'),
    path('add-member/<str:groupslug>', add_customer_to_group, name='add-member'),
    path('remove-member/<str:groupslug>', remove_customer_from_group, name='remove-member'),
    # path('update-group/<str:slug>/<str:groupslug>', update_user_group, name='update-group'),
    path('plangroup/<str:slug>/<str:plangroupslug>', show_plan_group, name='plangroup'),

]

dashboard/forms.py
from dataclasses import fields
from django import forms
from .models import customer
from plans.models import *

class CustomerCreateForm(forms.ModelForm):
    class Meta:
        model = customer
        fields = [ 'utility_name' ,'utility_short_name' ,'utility_state' ,'utility_district' ,'utility_country' ,'utility_postalcode' ,'utility_address' ,'contact_person' ,'contact_email' ,'contact_phnum' ,'contact_mobile' ,'contact_designation' ,'contact_landline' ,'emergency_person' ,'emergency_altperson' ,'emergency_mobile' ,'emergency_altmobile' ,'emergency_officeaddress' ,'emergency_altofficeaddress']
    
class UpdateProfilePlanForm(forms.Form):
    choice = [(1,1)]
    def __init__(self, appslug=None, profile=None, *args, **kwargs):
        super(UpdateProfilePlanForm, self).__init__(*args, **kwargs)
        plans = Plan.objects.filter(app__slug=appslug)
        plans_ = []
        for plan in plans:
            plan_ = (plan.id, plan)
            plans_.append(plan_)
        self.fields['update_to'].choices = plans_
        self.fields['paid'].initial = profile.paid
        self.fields['plan_active'].initial = profile.plan_active

    paid = forms.BooleanField(
        initial=False, 
        required=False,
        widget=forms.CheckboxInput(attrs={'placeholder': 'Default for every customer', 'class': 'w3-margin w3-check'}),
    )
    plan_active = forms.BooleanField(
        initial=False, 
        required=False,
        widget=forms.CheckboxInput(attrs={'placeholder': 'Default for every customer', 'class': 'w3-margin w3-check'}),
    )
    update_to = forms.ChoiceField(
        choices=choice, 
        widget=forms.Select(attrs={'placeholder': 'select plan for user ', 'class': 'w3-input w3-border w3-round'}),
    )

dashboard/views.py
import profile
from django.shortcuts import render
from django.shortcuts import render, redirect, get_object_or_404

from accounts.models import Profile
from .models import customer,csvs
from datetime import datetime
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from logging.handlers import TimedRotatingFileHandler
import logging
from plans.models import *
from apps.models import applists
from accounts.forms import NotificationForm
from accounts.models import Notification
from django.contrib import messages

logger=logging.getLogger()
logging.basicConfig(
        handlers=[ TimedRotatingFileHandler('logs.log', when="midnight", interval=1)],
        level=logging.DEBUG,
        format="[%(asctime)s] %(levelname)s [%(name)s.%(funcName)s:%(lineno)d] %(message)s",
        datefmt='%Y-%m-%dT%H:%M:%S')

from django.contrib.auth.models import User
from apps.models import applists

# Create your views here.
'''def addcustomer(request,slug):
    app=applists.objects.get(slug=slug)
    addcus=customer()
    if request.method=='POST':
        app=app
        utility_name = request.POST.get('utility_name')
        utility_short_name= request.POST.get('utility_short_name')
        utility_state= request.POST.get('utility_state')
        utility_district= request.POST.get('utility_district')
        utility_country=request.POST.get('utility_country')
        utility_postalcode= request.POST.get('utility_postalcode')
        utility_address=request.POST.get('utility_address')

        #contact details
        contact_person= request.POST.get('contact_person')
        contact_email = request.POST.get('contact_email')
        contact_phnum =request.POST.get('contact_phnum')
        contact_mobile=request.POST.get('contact_mobile')
        contact_designation= request.POST.get('contact_designation')
        contact_landline=request.POST.get('contact_landline')

        emergency_person=request.POST.get('emerg_person')
        emergency_altperson=request.POST.get('emerg_altperson')
        emergency_mobile=request.POST.get('emerg_mobile')
        emergency_altmobile=request.POST.get('emerg_altmobile')
        emergency_officeaddress=request.POST.get('emerg_officeaddress')
        emergency_altofficeaddress=request.POST.get('emerg_altofficeaddress')

        #contact details
        addcus.utility_name =utility_name
        addcus.utility_short_name = utility_short_name
        addcus.utility_state = utility_state
        addcus.utility_district = utility_district
        addcus.utility_country = utility_country
        addcus.utility_postalcode = utility_postalcode
        addcus.utility_address=utility_address

        addcus.contact_person = contact_person
        addcus.contact_email=contact_email
        addcus.contact_phnum=contact_phnum
        addcus.contact_mobile=contact_mobile
        addcus.contact_designation=contact_designation
        addcus.contact_landline=contact_landline

        addcus.emergency_person=emergency_person
        addcus.emergency_altperson=emergency_altperson
        addcus.emergency_mobile=emergency_mobile
        addcus.emergency_altmobile=emergency_altmobile
        addcus.emergency_officeaddress=emergency_officeaddress
        addcus.emergency_altofficeaddress=emergency_altofficeaddress

        addcus.save()
        return redirect('customerlist')
    else:
        return render(request, 'addcustomer.html',{'slug':slug})'''
from .forms import CustomerCreateForm

@login_required
def addcustomer(request):
    if request.method == 'POST':
        form = CustomerCreateForm(request.POST)
        if request.user == app.author:
            if form.is_valid():
                customer.objects.create(
                    utility_name = request.POST.get('utility_name'),
        utility_short_name= request.POST.get('utility_short_name'),
        utility_state= request.POST.get('utility_state'),
        utility_district= request.POST.get('utility_district'),
        utility_country=request.POST.get('utility_country'),
        utility_postalcode= request.POST.get('utility_postalcode'),
        utility_address=request.POST.get('utility_address'),
        contact_person= request.POST.get('contact_person'),
        contact_email = request.POST.get('contact_email'),
        contact_phnum =request.POST.get('contact_phnum'),
        contact_mobile=request.POST.get('contact_mobile'),
        contact_designation= request.POST.get('contact_designation'),
        contact_landline=request.POST.get('contact_landline'),
        emergency_person=request.POST.get('emerg_person'),
        emergency_altperson=request.POST.get('emerg_altperson'),
        emergency_mobile=request.POST.get('emerg_mobile'),
        emergency_altmobile=request.POST.get('emerg_altmobile'),
        emergency_officeaddress=request.POST.get('emerg_officeaddress'),
        emergency_altofficeaddress=request.POST.get('emerg_altofficeaddress'),
                )
                return redirect('customerlist', slug=slug)
        else :
            return redirect('home')
    else :
        form = CustomerCreateForm()
    return render(request, 'addcustomer.html', {'form' :form})

@login_required
def customerlist(request,slug, billing_slug):
    app=applists.objects.get(slug=slug)
    details = Profile.objects.filter(apps=app)
    return render(request, 'customerlist.html', {'details':details, 'slug':slug, 'billing_slug' : billing_slug})
    
@login_required
def deletecust(request,utility_name):
    deli=customer.objects.get(utility_name=utility_name)
    deli.delete()
    logger.info(request.user.username+"_deleted the"+deli.utility_name)
    return redirect('customerlist')

@login_required
def updaterecord(request,id):
    inst=customer.objects.get(id=id)
    if request.method=='POST':
        utility_name = request.POST.get('utility_name')
        utility_short_name= request.POST.get('utility_short_name')
        utility_state= request.POST.get('utility_state')
        utility_district= request.POST.get('utility_district')
        utility_country=request.POST.get('utility_country')
        utility_postalcode= request.POST.get('utility_postalcode')
        #contact details
        contact_person= request.POST.get('contact_person')
        contact_email = request.POST.get('contact_email')
        contact_phnum =request.POST.get('contact_phnum')
        contact_designation= request.POST.get('contact_designation')
        office_address=request.POST.get('office_address')
        instance=customer.objects.get(id=id)
        #contact details
        instance.utility_name =utility_name
        instance.utility_short_name = utility_short_name
        instance.utility_state = utility_state
        instance.utility_district = utility_district
        instance.utility_country = utility_country
        instance.utility_postalcode = utility_postalcode
        instance.contact_person = contact_person
        instance.contact_email=contact_email
        instance.contact_phnum=contact_phnum
        instance.contact_designation=contact_designation
        instance.office_address=office_address
        instance.save()

        return redirect('customerlist')
    else:
        return render(request, 'editcustomer.html',{'profile': inst})

import pandas as pd
@login_required
def bulk_upload(request,slug, billing_slug):
    if request.method=='POST':
        csvfile=request.FILES.get('csvfile')
        df=pd.read_csv(csvfile)
        l=list(df.columns)
        if l==['LatD', ' "LatM"', ' "LatS"', ' "NS"', ' "LonD"', ' "LonM"', ' "LonS"', ' "EW"', ' "City"', ' "State"']:
            objs = [csvs(
                LatD= row['LatD'],
                LatM  = row[' "LatM"'],
                LatS= row[' "LatS"'],
                NS= row[' "NS"'],
                LonD  = row[' "LonD"'],
                LonM  = row[' "LonM"'],
                LonS  = row[' "LonS"'],
                EW  = row[' "EW"'],
                City  = row[' "City"'],
                State= row[' "State"']
                )
            for i,row in df.iterrows()]
            csvs.objects.bulk_create(objs)
            return redirect('uploadlist')
        else:
            status=0
            return render(request, 'bulkupload.html',{'stat':status, 'slug':slug, 'billing_slug':billing_slug})
    else:
        stat=0
        return render(request, 'bulkupload.html',{'stat':stat, 'slug' : slug, 'billing_slug':billing_slug})
@login_required
def uploadlis(request, slug, billing_slug):
    cols=[f.name for f in csvs._meta.get_fields()]
    dets=csvs.objects.all()
    return render(request,'uploadlist.html',{'details':dets,'columns':cols, 'slug':slug, 'billing_slug':billing_slug})

@login_required
def dashboard(request, slug, billing_slug):
    return render(request, 'dashboard.html', {'slug' : slug, 'billing_slug':billing_slug})

@login_required
def estimate(request, slug, billing_slug):
    return render(request, 'dashestimate.html', {'slug' : slug, 'billing_slug':billing_slug})


@login_required
def transactions(request, slug, billing_slug):
    return render(request, 'dashtransactions.html', {'slug' : slug,'billing_slug':billing_slug})


@login_required
def appinfo(request, slug, billing_slug):
    app = applists.objects.get(slug=slug)
    if billing_slug:
        plan = app.plan_set.all().filter(default_for_customer=True)[0]
    else:
        plan = {}
    return render(request, 'dashappinfo.html', {'slug' : slug, 'app' : app,'plan':plan, 'billing_slug':billing_slug})





@login_required
def messaging(request, slug, billing_slug):
    if request.method == 'GET':
        notification_form = NotificationForm()
        app=applists.objects.get(slug=slug)
        details = Profile.objects.filter(apps=app)
        user_details = {}
        for detail in details:

templates/customerdashnav.html
{% load static %}
<header>
    <nav class="navbar navbar-expand-lg fixed-top p-md-0">
        <div class="container-fluid">
            <div class="d-md-none menu">
                <i class="fa-solid fa-bars"></i>
            </div>
            <div class="d-none d-md-none close">
                <i class="fa-solid fa-xmark fa-xl"></i>
            </div>
            <a class="navbar-brand d-none d-md-block mt-1" href="#">
                <h4 class="text-dark">Billsnap</h4>
            </a>
            <div class="d-flex ms-auto gap-4 pe-3">
                <div class="btn-group dropstart">
                    <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        <i class="fa-regular fa-bell"></i>
                    </button>
                    {% url 'customer-notifications-nav' %}
                    <ul class="dropdown-menu dropdown-menu-end mt-4">
                        {% for notification in notifications %}
                        <li><a class="dropdown-item" href="#">{{ notification.body }}</a></li>
                        {% endfor %}
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{% url 'customer-notifications' %}">View all Notifications</a></li>

                    </ul>
                </div>
                <div class="btn-group dropstart">
                    <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        <i class="fa-regular fa-user"></i>

                    </button>
                    <ul class="dropdown-menu dropdown-menu-end mt-4">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Separated link</a></li>
            
                    </ul>
                </div>

            </div>
        </div>
    </nav>
</header>

templates/dashnav.html
<style>
    .navbar .b-primary {
        all: unset;
        background: #3dcd58;
        color: white;
        box-shadow: 0px 0px 1px rgb(40 41 61 / 4%), 0px 2px 4px rgb(96 97 112 / 16%);
        border: 1px solid transparent;
        border-radius: 5px;
    }

    .navbar .b-secondary {
        background: white;
        color: black;
    }

    /* Dropdown content (hidden by default) */
    .dropdown-content {
        display: none;
        position: absolute;
        right:0px;
        background-color: #f9f9f9;
        min-width: 160px;
        box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);
        z-index: 1;
    }

    /* Links inside the dropdown */
    .dropdown-content a {
        float: none;
        color: black;
        padding: 12px 16px;
        text-decoration: none;
        display: block;
        text-align: left;
    }

    /* Add a grey background color to dropdown links on hover */
    .dropdown-content a:hover {
        background-color: #ddd;
    }

    /* Show the dropdown menu on hover */
    .dropdown:hover .dropdown-content {
        display: block;
    }
    .dropbtn{
        width:40px;
        height: 40px;
        border:none !important;
        border-radius:50%;
        background-color: white;
    }
    .fa-user{
     font-size: 23px;
    }
</style>
<header>
    <nav class="navbar navbar-expand-lg fixed-top p-md-0">
        <div class="container-fluid">
            <div class="d-md-none menu">
                <i class="fa-solid fa-bars"></i>
            </div>
            <div class="d-none d-md-none close">
                <i class="fa-solid fa-xmark fa-xl"></i>
            </div>
            <a class="navbar-brand d-none d-md-block mt-1" href="{% url 'index' %}">
                <h2 class="h2">BILL SNAP</h2>
            </a>
            {% if user.is_authenticated %}
            <div class="d-flex ms-auto gap-4 pe-3">
                <div class="dropdown">
                    <button class="dropbtn">
                        <i class="fa-solid fa-user text-secondary"></i>
                    </button>
                    <div class="dropdown-content">
                        <a href="#">View Profile</a>
                        <a href="#">View History</a>
                        <a href="{% url 'accounts:logout' %}">Logout</a>
                    </div>
                </div>
               

            </div>
            {% endif %}
        </div>
    </nav>
</header>

templates/dashsidebar.html
<style>
  .menu-frag a:active {
    color: blue;
    ;
  }

  .first-sidebar {
    position: fixed;
    top: 76px;
    left: 0;
  }

  .second {
    visibility: hidden;
  }
</style>
<div class="left first-sidebar d-none d-md-block col-md-4">
  <div class="menu-frag d-flex flex-column p-3 ps-4 gap-3">
    <div>
      <i class='bx bx-grid-alt'></i>

      <a href="{% url 'dashboard' billing_slug slug %} " id="active">Dashboard</a>
    </div>
    <div>
      <i class='bx bx-analyse'></i>

      <a href="{% url 'estimates' billing_slug slug %}">Estimates</a>
    </div>
    <div>
      <i class='bx bx-cog'></i>

      <a href="{% url 'appinfo' billing_slug slug %}">App Info</a>
    </div>
  </div>
  <hr>
  <div class="menu-frag mt-3 ps-3">
    <h4>Customer</h4>
    <div class="customer-frag d-flex flex-column p-3 pt-1 gap-3">
      <div>
        <i class='bx bx-box'></i>
        <a href="{% url 'addcustomer' billing_slug slug %}">Create</a>
      </div>
      <div>
        <i class='bx bx-box'></i>
        <a href="{% url 'customerlist' billing_slug slug %}">Customer List</a>
      </div>
      <div>
        <i class='bx bx-log-out'></i>
        <a href="{% url 'bulkupload' billing_slug slug %}">Bulk Upload</a>
      </div>
      <div>
        <i class='bx bx-archive-in'></i>
        <a href="{% url 'groups:groups-panel' billing_slug  slug %}">Manage Group</a>
      </div>
      <div>
        <i class='bx bx-bar-chart'></i>
        <a href="{% url 'pending-approvals' billing_slug slug %}">Pending approvals</a>
      </div>
      <div>
        <i class='bx bx-message'></i>
        <a href="{% url 'messaging' billing_slug slug %}">Messaging</a>
      </div>
    </div>
  </div>
  <hr>

  {% if billing_slug %}
  
  <div class="menu-frag mt-3 ps-3">
    <h4>Payments</h4>
    <div class="pay-frag d-flex flex-column  p-3 pt-1  gap-3">
      <div>
        <i class='bx bx-list-ul'></i>
        <a href="{% url 'transactions' billing_slug slug  %}">Transactions </a>
      </div>

      <div>
        <i class='bx bx-coin-stack'></i>
        <a href="{% url 'plans-panel' billing_slug slug  %}">Plans</a>
      </div>
      <div>
        <i class='bx bx-heart'></i>
        <a href="#">Requests</a>
      </div>
    </div>
  </div>
  {% endif %}


</div>
<div class="left second">

</div>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Login page</title>

<script src="{% static 'account/signin.js' %}"></script>
<script>
    function myFunction() {
      document.getElementById("myBtn").disabled = true;

    }
    </script>
    <style>
        button:disabled {
  cursor: not-allowed;
  pointer-events: all !important;
}


li.disabled {
  cursor: not-allowed;
}
li.disabled a {
  pointer-events: none;
}
    </style>
<link href="{% static 'account/login.css' %}" rel="stylesheet">
<link rel="shortcut icon" type="image/png" href="">
<link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@500&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Nunito&family=Poppins:wght@500&display=swap" rel="stylesheet">
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
crossorigin="anonymous"
        >
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="{% static 'assets/styles.css'%}">
</head>
<style>
    body{
        overflow:hidden;
    }
</style>
<body>
    {% include "dashnav.html" %}
<div class=" mt-5">
    <div class="row mt-5">
        <div class="col-md-12">
            {% include 'messages.html' %}
            <section class="contact-us-section mb-5 mt-3">
                <div class="contact-us-right mt-5">
                    <div class="contact-us-form-holder p-5">
                        <p class="heading">
                            Welcome Back!
                        </p>
                        <form action="{% url 'accounts:login' %}" method="POST" class="needs-validation"novalidate>
                        {% csrf_token %}
                            <label for="username" class="form-label">Username or Email Address</label>
                            {% if user_name %}
                            <input
                                class="form-control"
                                type="text"
                                placeholder="username"
                                name="username"
                                value={{user_name}}
                                required
                            >
                            {% else %}
                            <input
                                class="form-control"
                                type="text"
                                placeholder="username"
                                name="username"
                                required
                            >
                            {% endif %}
                                    <div class="invalid-feedback">
                                        Please choose a username.
                                    </div>

                            <label for="password" class="form-label">Password</label>
                            <input
                                class="form-control"
                                type="password"
                                placeholder="password"
                                name="password"
                                required
                            >
                                    <div class="invalid-feedback">
                                        Please provide a valid Password.
                                    </div>

                            {% if request.GET.next %}
                            <input type="hidden" name="next" value="{{request.GET.next}}">
                            {% endif %}
                            <button id="myBtn" class="button" name="login_page" type="submit">login</button>
                            <br>
                        <label><a id="forget_pass" href="{% url 'accounts:reset-password' %}">Forgot your password?</a></label>
                        </form>
                    </div>
                </div>
            </section>
        </div>

        <div class="col-md-12">
            <section class="contact-us-section">
                <div class="contact-us-right contact-us-right-bottom">
                    <div class="contact-us-form-holder">
                        <div class="contact-us-footer">
                            <p>
                                Or
                                <a href="{% url 'accounts:register' %}">Click Here</a>
                                to create account
                            </p>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>
</body>
</html>

templates/signup.html
{% block content %}
{% if error %}
{{ error }}
<br/>
<br/>
{% endif %}
<h1>Signup!</h1>
<form method = "POST" action="{% url 'signup' %}">
    {% csrf_token %}
    username:
    <br/>
    <input type="text" name="username" />
    <br/>
    email:
    <br/>
    <input type="email" name="email" />
    <br/>
    Password:
    <br/>
    <input type="password" name="password1" />
    <br/>
    confirm Password:
    <br/>
    <input type="password" name="password2" />
    <br/>
    <input class ="btn btn-primary" type="submit" value= "signup" />
    <br/>
</form>
{% endblock %}